name: Addyson Miller
favicon: null
layout_spectrum: 0.00411106669344008
typography_spectrum: 0.021246910328045487
title: 'Somewhere between a sloth and a soft space. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.9134449870325625
  rhythmicContrast: 0.75
purpose: []
