name: Addyson Miller
favicon: null
layout_spectrum: 1
typography_spectrum: 0.11138
title: 'Somewhere between a sloth and a soft space. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6e0c0'
    - '#030011'
    - '#31322d'
    - '#b7aa98'
    - '#a664b8'
  brandStrength: 0.6875
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
