name: Addyson Miller
favicon: null
layout_spectrum: 0.00411106669344008
typography_spectrum: 0.11138
title: 'Somewhere between a sloth and a soft space. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfbda'
    - '#bfc9af'
    - '#262432'
    - '#4c4e5a'
    - '#9c8375'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
